/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.NhanVienDAO;
import MODEL.NhanVien;
import Utils.hepper;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class findJdialog extends javax.swing.JInternalFrame {

    private Connection cn;
    private PreparedStatement ptm;
    private ResultSet rs;
    NhanVienDAO dao = new NhanVienDAO();

    String SELECT_ALL_SQL = "select * from NHANVIEN";
    String SELECT_ALL_SQL1 = "select * from NHANVIEN";

    /**
     * Creates new form findJdialog
     */
    public findJdialog() {
	initComponents();
	connection();
	init();
    }

    private void connection() {
	try {
	    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
	    cn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=DUAN1;user=sa;password=1");
	} catch (Exception ex) {
	    ex.printStackTrace();
	}
    }

    void init() {
	taikhoan();
	nhanvien1(SELECT_ALL_SQL);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblnahnvien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtnhanvien1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btntraikhoan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltaikhoan = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tblnahnvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Giới tính", "ĐIện thoại", "Email", "Vai trò"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblnahnvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblnahnvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblnahnvien);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Tìm kiếm");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Find.png"))); // NOI18N
        jButton1.setText("Tìm kiếm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnhanvien1, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnhanvien1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nhân viên", jPanel2);

        btntraikhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Find.png"))); // NOI18N
        btntraikhoan.setText("Tìm kiếm");
        btntraikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntraikhoanActionPerformed(evt);
            }
        });

        tbltaikhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Mật khẩu", "Tên nhân viên", "Vai trò"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbltaikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbltaikhoanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbltaikhoan);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 747, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(35, 649, Short.MAX_VALUE)
                        .addComponent(btntraikhoan)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btntraikhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tài khoản", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblnahnvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblnahnvienMouseClicked
	// TODO add your handling code here:

    }//GEN-LAST:event_tblnahnvienMouseClicked

    private void tbltaikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbltaikhoanMouseClicked
	// TODO add your handling code here:

    }//GEN-LAST:event_tbltaikhoanMouseClicked


    private void btntraikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntraikhoanActionPerformed
	// TODO add your handling code here:


    }//GEN-LAST:event_btntraikhoanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	// TODO add your handling code here:
	String sql = "select * from NHANVIEN where MANV like N'%" + txtnhanvien1.getText() + "%' or HOTEN like N'%" + txtnhanvien1.getText() + "%'";
	nhanvien1(sql);
	txtnhanvien1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed
    void nhanvien() {
	DefaultTableModel tblmodel = (DefaultTableModel) tblnahnvien.getModel();
	tblmodel.setRowCount(0);
	try {

	    List<NhanVien> list = dao.selectAll();
	    for (NhanVien nv : list) {
		Object[] row = {
		    nv.getMANV(),
		    nv.getHOTEN(),
		    nv.isGIOITINH() ? "Nam" : "Nữ",
		    nv.getDIENTHOAI(),
		    nv.getEMAIL(),
		    nv.isVAITRO() ? "Quản Lý" : " Nhân Viên"
		};
		tblmodel.addRow(row);
	    }

	} catch (Exception e) {
	    e.printStackTrace();
	}
    }

    void nhanvien1(String sql) {
	DefaultTableModel tblmodel = (DefaultTableModel) tblnahnvien.getModel();
	tblmodel.setRowCount(0);
	try {
	    ptm = cn.prepareStatement(sql);
	    rs = ptm.executeQuery();

	    while (rs.next()) {
		Vector vecto = new Vector();
		vecto.add(rs.getString("MANV").trim());
		vecto.add(rs.getString("HOTEN").trim());
		vecto.add(rs.getBoolean("GIOITINH") ? "Nam" : "Nữ");
		vecto.add(rs.getString("DIENTHOAI").trim());
		vecto.add(rs.getString("EMAIL").trim());
		vecto.add(rs.getBoolean("VAITRO") ? "Quản lý" : "Nhân Viên");
		tblmodel.addRow(vecto);
	    }
	    tblnahnvien.setModel(tblmodel);
	} catch (Exception e) {
	    e.printStackTrace();
	}
    }

    void taikhoan() {
	DefaultTableModel tblmodel = (DefaultTableModel) tbltaikhoan.getModel();
	tblmodel.setRowCount(0);
	try {
	    List<NhanVien> list = dao.selectAll();
	    for (NhanVien nv : list) {
		Object[] row = {
		    nv.getMANV(), "****", nv.getHOTEN(), nv.isVAITRO() ? "Quản Lý" : " Nhân Viên"
		};
		tblmodel.addRow(row);
	    }
	} catch (Exception e) {
	    e.printStackTrace();
	}
    }

    void taikhoan1(String sql) {
	DefaultTableModel model = (DefaultTableModel) tbltaikhoan.getModel();
	model.setRowCount(0);
	try {

	    ptm = cn.prepareStatement(sql);
	    rs = ptm.executeQuery();
	    while (rs.next()) {
		Vector vecto = new Vector();
		vecto.add(rs.getString("MANV").trim());
		vecto.add(rs.getString("*****"));
		vecto.add(rs.getString("HOTEN").trim());
		vecto.add(rs.getBoolean("VAITRO") ? "Quản lý" : "Nhân Viên");
		model.addRow(vecto);
	    }
	    tbltaikhoan.setModel(model);
	} catch (Exception e) {
	}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntraikhoan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblnahnvien;
    private javax.swing.JTable tbltaikhoan;
    private javax.swing.JTextField txtnhanvien1;
    // End of variables declaration//GEN-END:variables
}
