/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import DAO.NhanVienDAO;
import MODEL.NhanVien;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Sencode extends javax.swing.JFrame {

    private int randumCode;

    /**
     * Creates new form Sencode
     */
    public Sencode() {
	initComponents();
	setLocationRelativeTo(null);
    }

    public static boolean checkCode(String txt) {
	// txt.setBackground(white);
	// String id = txt.getText;
	String rgx = "[0-9]{6}";
	if (txt.matches(rgx)) {
	    return true;
	} else {
	    // txt.setBackground(pink);
	    JOptionPane.showMessageDialog(null, " phải là số và có đúng 6 số");
	    return false;
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtten = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnsend = new javax.swing.JButton();
        Btnthoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tên nhân viên");

        txtten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenActionPerformed(evt);
            }
        });

        jLabel2.setText("Email");

        btnsend.setText("Sendcode");
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });

        Btnthoat.setText("Exit");
        Btnthoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnthoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btnthoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsend))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btnthoat))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnthoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnthoatActionPerformed
	// TODO add your handling code here:
	int hoi = JOptionPane.showConfirmDialog(this, "bạn muốn kết thúc ?");
	if (hoi != JOptionPane.YES_NO_OPTION) {
	    return;
	}
	this.dispose();
    }//GEN-LAST:event_BtnthoatActionPerformed

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed
	// TODO add your handling code here:
	try {
	    Random random = new Random();
	    this.randumCode = random.nextInt(999999);//tạo 1 số ngẫu nhiên từ 0 đến 999999
	    String host = "smtp.gmail.com";
	    String user = "duongdvph14918@fpt.edu.vn";
	    String pass = "Anhduong2k1";
	    String to = txtEmail.getText();
	    String subject = "Reseting Code";
	    String message = "Your reset code is " + randumCode;
	    boolean sessionDebug = false;
	    //!.Tạo 1 dối tượng Properties
	    Properties pros = new Properties();
	    pros.put("mail.smtp.auth", "true");
	    pros.put("mail.smtp.starttls.enable", "true");
	    pros.put("mail.smtp.host", "smtp.gmail.com");//2.Chỉ ra máy chủ mail của gg
	    pros.put("mail.smtp.port", 587);//3.Chỉ ra port : 587 Cổng vào ra dữ liệu
	    pros.put("mail.smtp.starttls.required", "true");
	    java.security.Security.addProvider(new com.sun.net.ssl.internal.ssl.Provider());

	    Session mailSession = Session.getInstance(pros,
		    new javax.mail.Authenticator() {
		protected PasswordAuthentication getPasswordAuthentication() {
		    return new PasswordAuthentication(user, pass);//Tài khoản Gmail của bạn và pass
		}
	    }
	    );
	    mailSession.setDebug(sessionDebug);
	    Message msg = new MimeMessage(mailSession);
	    //Gán giá trị cho các thuộc tính đôi tượng msg
	    msg.setFrom(new InternetAddress(user));//5.Từ địa chỉ Gmail nào gưởi đi
	    //            InternetAddress[] address = {new InternetAddress(to)};
	    msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));//Tù Gmail gưởi đến mai nào
	    msg.setSubject(subject);//Tiêu đề thư
	    msg.setText(message);//Nội dung thư
////            Transport.send(msg);
	    Transport transport = mailSession.getTransport("smtp");
	    transport.connect(host, user, pass);
	    transport.sendMessage(msg, msg.getAllRecipients());
	    transport.close();
	    this.dispose();
	    JOptionPane.showMessageDialog(this, "Code has been send to the email");
	    String macodeString = JOptionPane.showInputDialog("Nhập vào mã Code (6 số)");

	    if (checkCode(macodeString)) {

		if (Integer.valueOf(macodeString) != randumCode) {
		    JOptionPane.showMessageDialog(this, "code bạn nhập không đúng");

		} else {
		    dmksendcode dk = new dmksendcode(this,true,txtten);
		    this.setVisible(false);
		    dk.setVisible(true);
		    
		}
	    } else {
		JOptionPane.showMessageDialog(this, "Bạn không được nhập chữ");
	    }
	} catch (Exception e) {
	    e.printStackTrace();

	}
    }//GEN-LAST:event_btnsendActionPerformed

    private void txttenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenActionPerformed
	// TODO add your handling code here:
	check();
    }//GEN-LAST:event_txttenActionPerformed
    boolean check() {
	NhanVienDAO dao = new NhanVienDAO();
	NhanVien nv = dao.selectByID(txtten.getText());
	if (nv == null) {
	    JOptionPane.showMessageDialog(this, "Tên nhân viên của bạn không tồn tại");
	    return true;
	} else {
	    txtEmail.setText(nv.getEMAIL());
	    return true;
	}

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Sencode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Sencode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Sencode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Sencode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Sencode().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnthoat;
    private javax.swing.JButton btnsend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables
}
